spring:
  redis:
    host: redis-14570.c305.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 14570
    password: xxxxxxxxxxx
  data:
    mongodb:
      uri: mongodb+srv://xxxxxxxxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxx.ngbwu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxxxxxxxxxxxx
    password: xxxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: xxxxxxxxxxxxxxxxxxxxx


#
#  kafka:
#    bootstrap-servers: pkc-9q8rv.ap-south-2.aws.confluent.cloud:9092
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#    consumer:
#      group-id: week1v-sentiment-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: net.engineeringdigest.journalApp.model
#
#    properties:
#      security:
#        protocol: SASL_SSL
#      sasl:
#        mechanism: PLAIN
#        jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='xxxxxxxxxxxxx' password='xxxxxxxxxxxxxxxx;
#
#    session:
#      timeout:
#        ms: 45000
#
#
#

#logging:
#  level:
#    root: ERROR
